### ISSUE TITLE
styled text

### ISSUE THREAD

**Issue by mikebutts** [ritsarassi/Colmar_academy#2]
![image](https://user-images.githubusercontent.com/8017734/40057718-0b591ed2-581d-11e8-8793-0847969595e4.png)

I like the styled text here , the only issue is, it is a bit hard to read. When picking out fonts you have to consider your audience and if you have any elderly or hard of sight, you might want to make the text clear as possible

**Comment by ritsarassi** [comment]
Changed to more easier to read style
