### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [ritsarassi/Colmar_academy#3]
Exceeds Expectations

Great job on this project it looks like an improved version of the spec! You did an awesome job adding extra styling with fonts, colors, mouse-overs, good job. I didn't run any any code issues, it was neat with proper tags, great use of flex in the different sections.  Great Job! Next, try to spice up the page, maybe add a color scheme, use www.coolors.co or add on more pages. With some customization, this could be a good piece to showcase flex use on a portfolio.

**Comment by ritsarassi** [comment]
Thanks for review! Changed some styles and all colors.
